[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc = "0.8.17"
optimizer = true
optimizer_runs = 200
fs_permissions = [
    { access = "read-write", path = "./script/network/" }
]

[fmt]
line_length = 120
tab_width = 4
style = "space"
bracket_spacing = false
int_types = "long"
quote_style = "double"
number_underscore = "preserve"
hex_underscore = "preserve"
single_line_statement_blocks = "multi"
wrap_comments = false
sort_imports = true
