// AI edit boundary: sample protocol state, labels, and fixture data live here.
// Keep rendering logic in app.js; add or alter chats/messages here first.
window.LOVE20_CHAT_PROTOTYPE_DATA = {
  initialState: {
  account: '0x8b...91',
  walletConnected: true,
  defaultGroupId: 9007,
  bottomTab: 'chat',
  view: 'inbox',
  inboxFilter: 'all',
  activationType: 'token',
  activationDrafts: {},
  activeToken: 'LOVE20A',
  activeGroupId: '1024',
  activeGroupNumericId: 1024,
  pageReturnStack: [],
  blacklistQuery: '',
  blacklistQueryType: 'address',
  blacklistQueryResult: '',
  blacklistPage: 1,
  activeBlacklistMenuKey: null,
  activeExemptMenuKey: null,
  adminIdQueryType: 'name',
  nftInputMode: 'name',
  delegateQueryResult: '',
  adminIdQuery: '',
  adminIdQueryResult: '',
  activeGovVoterTargetType: null,
  activeGovVoterTarget: null,
  voterPage: 1,
  voterQuery: '',
  voterQueryResult: '',
  revalidateVoter: '0x3a...02',
  quotedMessagesByGroupId: {},
  readCursorsByGroupId: {
    1024: 2,
    1188: 31,
    1301: 11,
    1302: 3,
  },
  mentionedSenderIds: [],
  mentionAll: false,
  activeMenuMessageId: null,
  activeAvatarMenuKey: null,
  activeGroupMenuId: null,
  syncHint: '',
  nftProfiles: {
    9001: { name: '行动发起人', badge: '行' },
    9007: { name: '北极熊', badge: '北' },
    1029: { name: '验证员小周', badge: '周' },
    1308: { name: '链群服务者', badge: '服' },
    1309: { name: '代理运营员', badge: '代' },
    1310: { name: '链群管理员', badge: '管' },
    9101: { name: '治理观察员', badge: '治' },
  },
  groupOwners: {
    9001: '0x3a...02',
    9007: '0x8b...91',
    1029: '0x52...13',
    1308: '0x21...ce',
    1309: '0x90...09',
    1310: '0x31...10',
    9011: '0x44...aa',
    9017: '0x66...d0',
    9050: '0x55...50',
    9101: '0x77...10',
  },
  defaultGroupIdsByAddress: {
    '0x3a...02': '9001',
    '0x8b...91': '9007',
    '0x52...13': '1029',
    '0x21...ce': '1308',
    '0x66...d0': '9017',
    '0x77...10': '9101',
  },
  actions: [
    { token: 'LOVE20A', actionId: '77', title: '春节公益铸造', round: 42, actionGroupId: 1188, actionGovGroupId: 1189 },
    { token: 'LOVE20A', actionId: '88', title: 'LP 激励迁移', round: 42, actionGroupId: 1190, actionGovGroupId: 1191 },
    { token: 'LOVE20B', actionId: '19', title: '社区验证扩容', round: 12, actionGroupId: 2190, actionGovGroupId: 2191 },
  ],
  chats: [
    {
      groupId: 1024,
      title: 'LOVE20A 社区群',
      shortTitle: '社区群',
      token: 'LOVE20A',
      tokenAddress: '0x1111111111111111111111111111111111111111',
      type: 'token-community',
      typeLabel: '代币社区群聊',
      model: 'decentralized',
      manager: 'TokenGroupChatManager',
      activationCall: 'activate(token)',
      params: { token: '0x1111111111111111111111111111111111111111' },
      activated: true,
      postingAllowed: true,
      immutableAfterActivate: true,
      round: 42,
      lastMessageId: 3,
      scopeAllowed: true,
      voteWeight: 18,
      voteWeightLabel: 'token 治理票',
      chatInfo: {
        scopeSource: 'TokenGroupChatManager',
        denySource: 'GovVotedDenySource',
        beforePostPlugin: 'address(0)',
        afterPostPlugin: 'address(0)',
        delegateId: '0',
      },
      blacklistMode: 'gov',
      govDeny: {
        stateVersion: 7,
        addressTargets: [
          { target: '0x44...aa', support: 43, oppose: 12, voters: 5, myVote: null, myWeight: 0, voterList: [
            { voter: '0x3a...02', stance: '支持', weight: 18 },
            { voter: '0x52...13', stance: '支持', weight: 13 },
            { voter: '0x66...d0', stance: '反对', weight: 12 },
          ] },
        ],
        senderIdTargets: [
          { target: '9011', support: 24, oppose: 2, voters: 3, myVote: 'support', myWeight: 18, voterList: [
            { voter: '0x8b...91', stance: '支持', weight: 18 },
            { voter: '0x21...ce', stance: '支持', weight: 6 },
            { voter: '0x66...d0', stance: '反对', weight: 2 },
          ] },
        ],
      },
    },
    {
      groupId: 1025,
      title: 'LOVE20A 治理者群',
      shortTitle: '治理群',
      token: 'LOVE20A',
      tokenAddress: '0x1111111111111111111111111111111111111111',
      type: 'token-gov',
      typeLabel: '代币治理者群聊',
      model: 'decentralized',
      manager: 'TokenGovGroupChatManager',
      activationCall: 'activate(token)',
      params: { token: '0x1111111111111111111111111111111111111111' },
      activated: false,
      postingAllowed: false,
      immutableAfterActivate: true,
      round: 42,
      lastMessageId: 0,
      scopeAllowed: true,
      voteWeight: 18,
      voteWeightLabel: 'token 治理票',
      chatInfo: {
        scopeSource: 'TokenGovGroupChatManager',
        denySource: 'GovVotedDenySource',
        beforePostPlugin: 'address(0)',
        afterPostPlugin: 'address(0)',
        delegateId: '0',
      },
      blacklistMode: 'gov',
      govDeny: { stateVersion: 0, addressTargets: [], senderIdTargets: [] },
    },
    {
      groupId: 1188,
      title: 'LOVE20A 行动 #77 群',
      shortTitle: '行动群 #77',
      token: 'LOVE20A',
      tokenAddress: '0x1111111111111111111111111111111111111111',
      actionId: '77',
      type: 'action',
      typeLabel: '代币行动群聊',
      model: 'decentralized',
      manager: 'TokenActionGroupChatManager',
      activationCall: 'activate(token, actionId)',
      params: { token: '0x1111111111111111111111111111111111111111', actionId: '77' },
      activated: true,
      postingAllowed: true,
      immutableAfterActivate: true,
      round: 42,
      lastMessageId: 32,
      scopeAllowed: false,
      voteWeight: 9,
      voteWeightLabel: '当前行动轮投票数',
      chatInfo: {
        scopeSource: 'TokenActionGroupChatManager',
        denySource: 'GovVotedDenySource',
        beforePostPlugin: 'address(0)',
        afterPostPlugin: 'address(0)',
        delegateId: '0',
      },
      blacklistMode: 'gov',
      govDeny: {
        stateVersion: 3,
        addressTargets: [],
        senderIdTargets: [
          { target: '9020', support: 13, oppose: 15, voters: 4, myVote: null, myWeight: 0, voterList: [
            { voter: '0x3a...02', stance: '支持', weight: 9 },
            { voter: '0x52...13', stance: '反对', weight: 15 },
          ] },
        ],
      },
    },
    {
      groupId: 1189,
      title: 'LOVE20A 行动 #77 治理群',
      shortTitle: '行动治理 #77',
      token: 'LOVE20A',
      tokenAddress: '0x1111111111111111111111111111111111111111',
      actionId: '77',
      type: 'action-gov',
      typeLabel: '代币行动治理者群聊',
      model: 'decentralized',
      manager: 'TokenActionGovGroupChatManager',
      activationCall: 'activate(token, actionId)',
      params: { token: '0x1111111111111111111111111111111111111111', actionId: '77' },
      activated: false,
      postingAllowed: false,
      immutableAfterActivate: true,
      round: 42,
      lastMessageId: 0,
      scopeAllowed: true,
      voteWeight: 9,
      voteWeightLabel: '当前行动轮投票数',
      chatInfo: {
        scopeSource: 'TokenActionGovGroupChatManager',
        denySource: 'GovVotedDenySource',
        beforePostPlugin: 'address(0)',
        afterPostPlugin: 'address(0)',
        delegateId: '0',
      },
      blacklistMode: 'gov',
      govDeny: { stateVersion: 0, addressTargets: [], senderIdTargets: [] },
    },
    {
      groupId: 1190,
      title: 'LOVE20A 行动 #88 群',
      shortTitle: '行动群 #88',
      token: 'LOVE20A',
      tokenAddress: '0x1111111111111111111111111111111111111111',
      actionId: '88',
      type: 'action',
      typeLabel: '代币行动群聊',
      model: 'decentralized',
      manager: 'TokenActionGroupChatManager',
      activationCall: 'activate(token, actionId)',
      params: { token: '0x1111111111111111111111111111111111111111', actionId: '88' },
      activated: false,
      postingAllowed: false,
      immutableAfterActivate: true,
      round: 42,
      lastMessageId: 0,
      scopeAllowed: true,
      voteWeight: 0,
      voteWeightLabel: '当前行动轮投票数',
      chatInfo: {
        scopeSource: 'TokenActionGroupChatManager',
        denySource: 'GovVotedDenySource',
        beforePostPlugin: 'address(0)',
        afterPostPlugin: 'address(0)',
        delegateId: '0',
      },
      blacklistMode: 'gov',
      govDeny: { stateVersion: 0, addressTargets: [], senderIdTargets: [] },
    },
    {
      groupId: 1191,
      title: 'LOVE20A 行动 #88 治理群',
      shortTitle: '行动治理 #88',
      token: 'LOVE20A',
      tokenAddress: '0x1111111111111111111111111111111111111111',
      actionId: '88',
      type: 'action-gov',
      typeLabel: '代币行动治理者群聊',
      model: 'decentralized',
      manager: 'TokenActionGovGroupChatManager',
      activationCall: 'activate(token, actionId)',
      params: { token: '0x1111111111111111111111111111111111111111', actionId: '88' },
      activated: false,
      postingAllowed: false,
      immutableAfterActivate: true,
      round: 42,
      lastMessageId: 0,
      scopeAllowed: true,
      voteWeight: 0,
      voteWeightLabel: '当前行动轮投票数',
      chatInfo: {
        scopeSource: 'TokenActionGovGroupChatManager',
        denySource: 'GovVotedDenySource',
        beforePostPlugin: 'address(0)',
        afterPostPlugin: 'address(0)',
        delegateId: '0',
      },
      blacklistMode: 'gov',
      govDeny: { stateVersion: 0, addressTargets: [], senderIdTargets: [] },
    },
    {
      groupId: 2190,
      title: 'LOVE20B 行动 #19 群',
      shortTitle: '行动群 #19',
      token: 'LOVE20B',
      tokenAddress: '0x2222222222222222222222222222222222222222',
      actionId: '19',
      type: 'action',
      typeLabel: '代币行动群聊',
      model: 'decentralized',
      manager: 'TokenActionGroupChatManager',
      activationCall: 'activate(token, actionId)',
      params: { token: '0x2222222222222222222222222222222222222222', actionId: '19' },
      activated: false,
      postingAllowed: false,
      immutableAfterActivate: true,
      round: 12,
      lastMessageId: 0,
      scopeAllowed: true,
      voteWeight: 0,
      voteWeightLabel: '当前行动轮投票数',
      chatInfo: {
        scopeSource: 'TokenActionGroupChatManager',
        denySource: 'GovVotedDenySource',
        beforePostPlugin: 'address(0)',
        afterPostPlugin: 'address(0)',
        delegateId: '0',
      },
      blacklistMode: 'gov',
      govDeny: { stateVersion: 0, addressTargets: [], senderIdTargets: [] },
    },
    {
      groupId: 2191,
      title: 'LOVE20B 行动 #19 治理群',
      shortTitle: '行动治理 #19',
      token: 'LOVE20B',
      tokenAddress: '0x2222222222222222222222222222222222222222',
      actionId: '19',
      type: 'action-gov',
      typeLabel: '代币行动治理者群聊',
      model: 'decentralized',
      manager: 'TokenActionGovGroupChatManager',
      activationCall: 'activate(token, actionId)',
      params: { token: '0x2222222222222222222222222222222222222222', actionId: '19' },
      activated: false,
      postingAllowed: false,
      immutableAfterActivate: true,
      round: 12,
      lastMessageId: 0,
      scopeAllowed: true,
      voteWeight: 0,
      voteWeightLabel: '当前行动轮投票数',
      chatInfo: {
        scopeSource: 'TokenActionGovGroupChatManager',
        denySource: 'GovVotedDenySource',
        beforePostPlugin: 'address(0)',
        afterPostPlugin: 'address(0)',
        delegateId: '0',
      },
      blacklistMode: 'gov',
      govDeny: { stateVersion: 0, addressTargets: [], senderIdTargets: [] },
    },
    {
      groupId: 1301,
      title: '链群 #1301 服务群',
      shortTitle: '链群 #1301',
      chainName: '雪松节点',
      token: 'LOVE20A',
      type: 'chain-service',
      typeLabel: '链群服务者管理型群聊',
      model: 'chain-service',
      role: 'owner',
      manager: 'GroupChat owner / delegate',
      activationCall: 'activateChat(...)',
      params: { groupId: '1301', scopeSource: 'GroupJoinScopeSource', denySource: 'AdminDenySource' },
      activated: true,
      postingAllowed: true,
      defaultGroupOwnerMatches: false,
      immutableAfterActivate: false,
      round: 42,
      lastMessageId: 12,
      scopeAllowed: true,
      chatInfo: {
        scopeSource: 'GroupJoinScopeSource',
        denySource: 'AdminDenySource',
        beforePostPlugin: 'address(0)',
        afterPostPlugin: 'address(0)',
        delegateId: '1309',
      },
      blacklistMode: 'admin',
      adminDeny: {
        stateVersion: 12,
        adminIds: ['1308', '1310'],
        addressDenyList: ['0x66...d0'],
        senderIdDenyList: ['9017'],
        senderIdExemptList: ['1309'],
      },
    },
    {
      groupId: 1302,
      title: '链群 #1302 服务群',
      shortTitle: '链群 #1302',
      chainName: '北海验证节点',
      token: 'LOVE20A',
      type: 'chain-service',
      typeLabel: '链群服务者管理型群聊',
      model: 'chain-service',
      role: 'admin',
      manager: 'GroupChat owner / delegate',
      activationCall: 'activateChat(...)',
      params: { groupId: '1302', scopeSource: 'GroupJoinScopeSource', denySource: 'AdminDenySource' },
      activated: true,
      postingAllowed: true,
      immutableAfterActivate: false,
      round: 42,
      lastMessageId: 4,
      scopeAllowed: true,
      chatInfo: {
        scopeSource: 'GroupJoinScopeSource',
        denySource: 'AdminDenySource',
        beforePostPlugin: 'address(0)',
        afterPostPlugin: 'address(0)',
        delegateId: '0',
      },
      blacklistMode: 'admin',
      adminDeny: {
        stateVersion: 4,
        adminIds: ['9007'],
        addressDenyList: [],
        senderIdDenyList: ['9050'],
        senderIdExemptList: [],
      },
    },
    {
      groupId: 1303,
      title: '链群 #1303 服务群',
      shortTitle: '链群 #1303',
      chainName: '公共服务节点',
      token: 'LOVE20A',
      type: 'chain-service',
      typeLabel: '链群服务者管理型群聊',
      model: 'chain-service',
      role: 'owner',
      manager: 'GroupChat owner / delegate',
      activationCall: 'activateChat(...)',
      params: { groupId: '1303', scopeSource: 'GroupJoinScopeSource', denySource: 'AdminDenySource' },
      activated: false,
      postingAllowed: false,
      immutableAfterActivate: false,
      round: 42,
      lastMessageId: 0,
      scopeAllowed: true,
      chatInfo: {
        scopeSource: 'GroupJoinScopeSource',
        denySource: 'AdminDenySource',
        beforePostPlugin: 'address(0)',
        afterPostPlugin: 'address(0)',
        delegateId: '0',
      },
      blacklistMode: 'admin',
      adminDeny: {
        stateVersion: 0,
        adminIds: [],
        addressDenyList: [],
        senderIdDenyList: [],
        senderIdExemptList: [],
      },
    },
    {
      groupId: 1304,
      title: '链群 #1304 服务群',
      shortTitle: '链群 #1304',
      chainName: '代理运营节点',
      token: 'LOVE20A',
      type: 'chain-service',
      typeLabel: '链群服务者管理型群聊',
      model: 'chain-service',
      role: 'delegate',
      manager: 'GroupChat owner / delegate',
      activationCall: 'activateChat(...)',
      params: { groupId: '1304', scopeSource: 'GroupJoinScopeSource', denySource: 'AdminDenySource' },
      activated: true,
      postingAllowed: true,
      immutableAfterActivate: false,
      round: 42,
      lastMessageId: 6,
      scopeAllowed: true,
      chatInfo: {
        scopeSource: 'GroupJoinScopeSource',
        denySource: 'AdminDenySource',
        beforePostPlugin: 'address(0)',
        afterPostPlugin: 'address(0)',
        delegateId: '9007',
      },
      blacklistMode: 'admin',
      adminDeny: {
        stateVersion: 5,
        adminIds: ['9007'],
        addressDenyList: [],
        senderIdDenyList: [],
        senderIdExemptList: ['9007'],
      },
    },
  ],
  messages: [
    { groupId: '1024', senderId: 9001, senderAddress: '0x3a...02', round: 42, messageId: 1, content: '本轮行动投票窗口已经开始，建议先确认治理票。', mentionedSenderIds: [], mentionAll: false, quotedMessageId: 0, mine: false },
    { groupId: '1024', senderId: 9007, senderAddress: '0x8b...91', round: 42, messageId: 2, content: '@验证员小周 我补充：MessagePost 只是发现信号，正文回查 messages。', mentionedSenderIds: [1029], mentionAll: false, quotedMessageId: 0, mine: true },
    { groupId: '1024', senderId: 1029, senderAddress: '0x52...13', round: 42, messageId: 3, content: '@全部 mentionAll 只记录声明语义，主协议不做许可判断。', mentionedSenderIds: [], mentionAll: true, quotedMessageId: 2, mine: false },
    { groupId: '1188', senderId: 9001, senderAddress: '0x3a...02', round: 42, messageId: 32, content: '@北极熊 行动 #77 需要你确认投票窗口。', mentionedSenderIds: [9007], mentionAll: false, quotedMessageId: 0, mine: false },
    { groupId: '1301', senderId: 1308, senderAddress: '0x21...ce', round: 42, messageId: 12, content: 'AdminDenySource 已按 groupId 隔离，黑名单只影响后续发言。', mentionedSenderIds: [], mentionAll: false, quotedMessageId: 0, mine: false },
    { groupId: '1302', senderId: 1308, senderAddress: '0x21...ce', round: 42, messageId: 4, content: '当前默认 NFT 是管理员时，点击头像可拉黑这个 sender。', mentionedSenderIds: [], mentionAll: false, quotedMessageId: 0, mine: false },
  ],
},

  bottomTabs: [
  { id: 'chat', label: '爱聊' },
  { id: 'actions', label: '行动' },
  { id: 'discover', label: '发现' },
  { id: 'me', label: '我的' },
],

  inboxFilters: [
  { id: 'all', label: '推荐' },
  { id: 'group', label: '群聊' },
  { id: 'managed', label: '我的' },
],

  activationTabs: [
  { id: 'token', label: '代币群' },
  { id: 'action', label: '行动群' },
  { id: 'chain', label: '链群' },
],

  pageSizes: {
    blacklist: 4,
    voter: 2,
  },
};
